export type Dimension =
  | "commitment"
  | "activity"
  | "social"
  | "patience"
  | "care"
  | "resources"
  | "specialist"
  | "safety"
  | "independence"
  | "adaptability"
  | "trainability"
  | "sensitivity";
export type Question = {
  id: string;
  text: string;
  weights: Partial<Record<Dimension, number>>;
  kind: "lifestyle" | "personality";
};
export type Recommendation = {
  id: string;
  title: string;
  petType: string;
  emoji: string;
  example: string;
  ideal: Record<Dimension, number>;
  reason: string;
  checks: string[];
};
const q = (
  id: string,
  text: string,
  dimension: Dimension,
  kind: Question["kind"] = "lifestyle",
): Question => ({ id, text, weights: { [dimension]: 1 }, kind });

// 保留 25 道现实照护题；原 q08、q10、q17、q20、q24 因信息重复度较高而移除。
export const questions: Question[] = [
  q("q01", "我每天都能稳定安排时间照顾宠物，而不只是周末有空。", "commitment"),
  q(
    "q02",
    "即使学习或工作变忙，我也愿意保持固定的喂食和清洁安排。",
    "commitment",
  ),
  q("q03", "我能接受连续多年承担同一只宠物的照护责任。", "commitment"),
  q("q04", "家中成年人或共同居住者支持饲养宠物。", "safety"),
  q("q05", "如果我是未成年人，监护人愿意承担最终照护和费用责任。", "safety"),
  q("q06", "我的住所明确允许饲养我考虑的宠物。", "safety"),
  q("q07", "我能提供与宠物体型和活动需求相符的安全空间。", "activity"),
  q("q09", "我喜欢每天散步、跑动或参与户外活动。", "activity"),
  q("q11", "我希望宠物经常主动与我互动和陪伴。", "social"),
  q("q12", "我能接受宠物有时不想被抱或抚摸。", "independence"),
  q("q13", "我享受通过重复练习帮助宠物学习规则。", "trainability"),
  q("q14", "面对叫声、抓挠或意外排泄时，我能耐心处理。", "patience"),
  q("q15", "我愿意花时间了解动物行为，而不是简单归为“不听话”。", "patience"),
  q("q16", "我更喜欢安静、独立、相处有边界感的宠物。", "independence"),
  q("q18", "我能接受毛发、垫料、气味或少量环境杂乱。", "care"),
  q("q19", "我愿意定期清洁猫砂盆、水族箱或饲养箱。", "care"),
  q("q21", "我有稳定预算支付食物、用品和常规医疗。", "resources"),
  q("q22", "我能为突发医疗费用预留资金或制定可靠方案。", "resources"),
  q("q23", "我愿意寻找具备相应物种经验的兽医服务。", "specialist"),
  q("q25", "我愿意为特殊温湿度、照明或饮食持续投入。", "specialist"),
  q("q26", "家中没有尚未解决的严重动物过敏风险。", "safety"),
  q("q27", "家中成员和现有宠物能与新宠安全共处。", "safety"),
  q("q28", "旅行或假期时，我有可靠的代养安排。", "commitment"),
  q("q29", "选择宠物时，我会把健康和福利放在外形或网络热度之前。", "safety"),
  q("q30", "决定饲养前，我愿意咨询专业人士并做好长期计划。", "commitment"),
  q("p01", "在热闹聚会中，我通常会主动认识新朋友。", "social", "personality"),
  q(
    "p02",
    "独处一段时间会让我感到放松，而不是无聊。",
    "independence",
    "personality",
  ),
  q(
    "p03",
    "计划临时变化时，我通常能很快调整状态。",
    "adaptability",
    "personality",
  ),
  q(
    "p04",
    "我喜欢固定的作息和可预期的日常节奏。",
    "sensitivity",
    "personality",
  ),
  q(
    "p05",
    "遇到新游戏或新技能时，我愿意反复练习直到掌握。",
    "trainability",
    "personality",
  ),
  q(
    "p06",
    "我容易注意到声音、气味或环境中的细小变化。",
    "sensitivity",
    "personality",
  ),
  q(
    "p07",
    "周末我更想安排户外探索，而不是一直待在家里。",
    "activity",
    "personality",
  ),
  q("p08", "朋友情绪低落时，我会主动靠近并陪伴。", "social", "personality"),
  q(
    "p09",
    "面对慢热的人或动物，我愿意等对方主动靠近。",
    "patience",
    "personality",
  ),
  q(
    "p10",
    "我喜欢尝试新路线、新餐厅或陌生体验。",
    "adaptability",
    "personality",
  ),
];

const checks = [
  "确认住房许可、家庭支持与当地法规",
  "核算长期食物、用品及医疗预算",
  "先接触具体个体，并咨询兽医或正规救助机构",
];
const dimensions: Dimension[] = [
  "commitment",
  "activity",
  "social",
  "patience",
  "care",
  "resources",
  "specialist",
  "safety",
  "independence",
  "adaptability",
  "trainability",
  "sensitivity",
];
const vector = (
  values: Partial<Record<Dimension, number>>,
): Record<Dimension, number> =>
  Object.fromEntries(dimensions.map((d) => [d, values[d] ?? 0.5])) as Record<
    Dimension,
    number
  >;
const profile = (
  id: string,
  title: string,
  petType: string,
  emoji: string,
  breed: string,
  values: Partial<Record<Dimension, number>>,
  reason: string,
): Recommendation => ({
  id,
  title,
  petType,
  emoji,
  example: `推荐品种：${breed}`,
  ideal: vector(values),
  reason,
  checks,
});

export const recommendations: Recommendation[] = [
  profile(
    "chihuahua",
    "小巧警觉型",
    "犬类 · 超小型",
    "🐕",
    "吉娃娃",
    {
      commitment: 0.75,
      activity: 0.35,
      social: 0.55,
      care: 0.45,
      resources: 0.65,
      independence: 0.65,
      adaptability: 0.6,
      trainability: 0.55,
      sensitivity: 0.9,
    },
    "你偏好体型小、情感连接紧密又警觉的伙伴。吉娃娃仍需要社会化、口腔护理、保暖与温和训练。",
  ),
  profile(
    "toy-poodle",
    "聪明精致型",
    "犬类 · 小型",
    "🐩",
    "玩具贵宾犬",
    {
      commitment: 0.85,
      activity: 0.6,
      social: 0.85,
      patience: 0.85,
      care: 0.95,
      resources: 0.8,
      adaptability: 0.8,
      trainability: 0.95,
      sensitivity: 0.65,
    },
    "你享受学习与互动，也愿意投入梳剪护理。玩具贵宾犬聪明亲人，需要规律美容、口腔护理和陪伴。",
  ),
  profile(
    "shih-tzu",
    "温柔居家型",
    "犬类 · 小型",
    "🐕",
    "西施犬",
    {
      commitment: 0.8,
      activity: 0.35,
      social: 0.8,
      patience: 0.7,
      care: 0.95,
      resources: 0.8,
      independence: 0.4,
      adaptability: 0.65,
      trainability: 0.55,
      sensitivity: 0.6,
    },
    "你喜欢温和居家陪伴，并能承担高频毛发护理。西施犬需关注眼睛、呼吸、牙齿与高温环境风险。",
  ),
  profile(
    "corgi",
    "热情机灵型",
    "犬类 · 中小型",
    "🐕",
    "彭布罗克威尔士柯基犬",
    {
      commitment: 0.85,
      activity: 0.75,
      social: 0.8,
      patience: 0.75,
      care: 0.7,
      resources: 0.8,
      adaptability: 0.7,
      trainability: 0.85,
      sensitivity: 0.75,
    },
    "你喜欢活泼、机灵且参与感强的伙伴。柯基需要运动、训练、体重与脊背关节管理。",
  ),
  profile(
    "beagle",
    "好奇探索型",
    "犬类 · 中型",
    "🐕",
    "比格犬",
    {
      commitment: 0.85,
      activity: 0.85,
      social: 0.85,
      patience: 0.9,
      care: 0.6,
      resources: 0.8,
      independence: 0.7,
      adaptability: 0.85,
      trainability: 0.65,
      sensitivity: 0.8,
    },
    "你有探索欲，也愿意耐心面对自主性较强的伙伴。比格犬嗅觉驱动明显，需要防走失、召回训练和运动。",
  ),
  profile(
    "border-collie",
    "高能协作型",
    "犬类 · 中型",
    "🐕",
    "边境牧羊犬",
    {
      commitment: 0.95,
      activity: 1,
      social: 0.75,
      patience: 0.95,
      care: 0.65,
      resources: 0.85,
      adaptability: 0.9,
      trainability: 1,
      sensitivity: 0.9,
    },
    "你需要高强度活动与智力协作。边境牧羊犬学习快、精力高，需要持续任务、运动和情绪管理。",
  ),
  profile(
    "golden-retriever",
    "阳光陪伴型",
    "犬类 · 中大型",
    "🐕",
    "金毛寻回犬",
    {
      commitment: 0.95,
      activity: 0.85,
      social: 0.95,
      patience: 0.85,
      care: 0.8,
      resources: 0.9,
      independence: 0.25,
      adaptability: 0.85,
      trainability: 0.9,
      sensitivity: 0.55,
    },
    "你能接受稳定运动、训练与高频互动。金毛通常亲人、乐于协作，但仍需毛发护理与健康筛查。",
  ),
  profile(
    "labrador-retriever",
    "活力行动型",
    "犬类 · 中大型",
    "🐕",
    "拉布拉多寻回犬",
    {
      commitment: 0.95,
      activity: 0.95,
      social: 0.95,
      patience: 0.8,
      care: 0.6,
      resources: 0.9,
      independence: 0.3,
      adaptability: 0.9,
      trainability: 0.9,
      sensitivity: 0.45,
    },
    "你有很高的运动供给和互动意愿。拉布拉多通常外向可训练，需要持续运动、体重和关节管理。",
  ),
  profile(
    "samoyed",
    "社交雪团型",
    "犬类 · 中大型",
    "🐕",
    "萨摩耶犬",
    {
      commitment: 0.95,
      activity: 0.9,
      social: 0.95,
      patience: 0.85,
      care: 1,
      resources: 0.95,
      independence: 0.45,
      adaptability: 0.55,
      trainability: 0.75,
      sensitivity: 0.7,
    },
    "你喜欢热情社交，也能接受大量毛发护理。萨摩耶需要运动、降温、防走失和高频梳毛。",
  ),
  profile(
    "great-dane",
    "沉稳巨人型",
    "犬类 · 巨型",
    "🐕",
    "大丹犬",
    {
      commitment: 0.95,
      activity: 0.55,
      social: 0.85,
      patience: 0.85,
      care: 0.6,
      resources: 1,
      independence: 0.4,
      adaptability: 0.55,
      trainability: 0.75,
      sensitivity: 0.55,
    },
    "你偏好沉稳陪伴并有足够空间和预算。大丹犬体型巨大，需要早期训练、关节与胃扭转风险管理。",
  ),

  profile(
    "singapura",
    "袖珍好奇型",
    "猫类 · 小型",
    "🐈",
    "新加坡猫",
    {
      commitment: 0.8,
      activity: 0.75,
      social: 0.85,
      patience: 0.7,
      care: 0.55,
      resources: 0.8,
      independence: 0.45,
      adaptability: 0.8,
      trainability: 0.7,
      sensitivity: 0.7,
    },
    "你喜欢小巧、好奇又亲人的伙伴。新加坡猫通常活跃，需要互动、攀爬空间和健康筛查。",
  ),
  profile(
    "siamese",
    "健谈黏人型",
    "猫类 · 中型",
    "🐈",
    "暹罗猫",
    {
      commitment: 0.85,
      activity: 0.8,
      social: 1,
      patience: 0.75,
      care: 0.55,
      resources: 0.8,
      independence: 0.25,
      adaptability: 0.8,
      trainability: 0.8,
      sensitivity: 0.85,
    },
    "你期待高频交流并能接受较多叫声。暹罗猫通常社交、聪明，需要陪伴、游戏和稳定环境。",
  ),
  profile(
    "li-hua-cat",
    "灵动独立型",
    "猫类 · 中型",
    "🐈",
    "中国狸花猫",
    {
      commitment: 0.8,
      activity: 0.8,
      social: 0.55,
      patience: 0.75,
      care: 0.55,
      resources: 0.7,
      independence: 0.8,
      adaptability: 0.9,
      trainability: 0.65,
      sensitivity: 0.55,
    },
    "你重视陪伴，也尊重动物边界。中国狸花猫常活泼、适应力较强，具体性格仍取决于个体经历。",
  ),
  profile(
    "american-shorthair",
    "均衡家庭型",
    "猫类 · 中型",
    "🐈",
    "美国短毛猫",
    {
      commitment: 0.8,
      activity: 0.6,
      social: 0.7,
      patience: 0.7,
      care: 0.55,
      resources: 0.75,
      independence: 0.65,
      adaptability: 0.85,
      trainability: 0.6,
      sensitivity: 0.45,
    },
    "你喜欢均衡、较易适应家庭节奏的伙伴。美国短毛猫仍需要互动、体重管理和预防性医疗。",
  ),
  profile(
    "british-shorthair",
    "安静陪伴型",
    "猫类 · 中大型",
    "🐈",
    "英国短毛猫",
    {
      commitment: 0.8,
      activity: 0.35,
      social: 0.55,
      patience: 0.65,
      care: 0.6,
      resources: 0.8,
      independence: 0.8,
      adaptability: 0.7,
      trainability: 0.45,
      sensitivity: 0.35,
    },
    "你偏好安静、有边界感的相处。英国短毛猫常较沉稳，但仍需要互动、体重管理和健康筛查。",
  ),
  profile(
    "russian-blue",
    "敏感专一型",
    "猫类 · 中型",
    "🐈",
    "俄罗斯蓝猫",
    {
      commitment: 0.85,
      activity: 0.55,
      social: 0.55,
      patience: 0.85,
      care: 0.5,
      resources: 0.8,
      independence: 0.75,
      adaptability: 0.45,
      trainability: 0.65,
      sensitivity: 0.95,
    },
    "你能尊重慢热与规律。俄罗斯蓝猫常对环境变化较敏感，需要稳定作息、耐心互动和安全躲藏处。",
  ),
  profile(
    "ragdoll-cat",
    "温柔黏人型",
    "猫类 · 大型",
    "🐈",
    "布偶猫",
    {
      commitment: 0.9,
      activity: 0.4,
      social: 0.95,
      patience: 0.75,
      care: 0.9,
      resources: 0.95,
      independence: 0.2,
      adaptability: 0.65,
      trainability: 0.6,
      sensitivity: 0.6,
    },
    "你期待温柔、高频陪伴，也能承担长毛护理。布偶猫需要遗传健康筛查、室内安全和医疗预算。",
  ),
  profile(
    "maine-coon",
    "温和巨猫型",
    "猫类 · 大型",
    "🐈",
    "缅因猫",
    {
      commitment: 0.9,
      activity: 0.65,
      social: 0.8,
      patience: 0.8,
      care: 0.9,
      resources: 1,
      independence: 0.55,
      adaptability: 0.75,
      trainability: 0.7,
      sensitivity: 0.5,
    },
    "你喜欢体型较大、温和且有参与感的猫。缅因猫需要空间、梳毛、心脏与关节健康筛查。",
  ),
  profile(
    "norwegian-forest",
    "独立森林型",
    "猫类 · 大型",
    "🐈",
    "挪威森林猫",
    {
      commitment: 0.9,
      activity: 0.75,
      social: 0.6,
      patience: 0.75,
      care: 0.95,
      resources: 0.95,
      independence: 0.85,
      adaptability: 0.65,
      trainability: 0.55,
      sensitivity: 0.55,
    },
    "你喜欢独立、善于攀爬的大型长毛猫。挪威森林猫需要垂直空间、梳毛和遗传健康筛查。",
  ),
  profile(
    "bengal-cat",
    "高能探索型",
    "猫类 · 中大型",
    "🐈",
    "孟加拉猫",
    {
      commitment: 0.95,
      activity: 1,
      social: 0.75,
      patience: 0.95,
      care: 0.6,
      resources: 0.95,
      independence: 0.7,
      adaptability: 0.9,
      trainability: 0.9,
      sensitivity: 0.8,
    },
    "你能提供高强度游戏、训练和环境丰富化。孟加拉猫活跃聪明，并不适合只期待安静陪伴的家庭。",
  ),

  profile(
    "abyssinian-guinea-pig",
    "细致社群型",
    "小型宠物",
    "🐹",
    "阿比西尼亚豚鼠",
    {
      commitment: 0.75,
      activity: 0.35,
      social: 0.55,
      patience: 0.75,
      care: 0.9,
      resources: 0.75,
      specialist: 0.9,
      independence: 0.35,
      adaptability: 0.45,
      sensitivity: 0.7,
    },
    "你对规律环境维护有耐心。豚鼠通常需要同类陪伴、充足空间、维生素 C 和异宠兽医。",
  ),
  profile(
    "syrian-hamster",
    "夜间观察型",
    "小型宠物",
    "🐹",
    "叙利亚仓鼠",
    {
      commitment: 0.65,
      activity: 0.25,
      social: 0.2,
      patience: 0.8,
      care: 0.85,
      resources: 0.65,
      specialist: 0.7,
      independence: 1,
      adaptability: 0.45,
      sensitivity: 0.8,
    },
    "你能尊重独处边界和夜间作息。叙利亚仓鼠通常应单独饲养，需要深垫料、合适跑轮和足够空间。",
  ),
  profile(
    "dutch-rabbit",
    "耐心照护型",
    "小型宠物",
    "🐇",
    "荷兰兔",
    {
      commitment: 0.9,
      activity: 0.55,
      social: 0.65,
      patience: 0.95,
      care: 0.95,
      resources: 0.85,
      specialist: 0.95,
      independence: 0.55,
      adaptability: 0.5,
      trainability: 0.55,
      sensitivity: 0.8,
    },
    "你愿意投入空间、清洁和长期陪伴。荷兰兔需要安全活动区、牧草饮食、同伴评估和兔科兽医。",
  ),
  profile(
    "betta-fish",
    "静心水景型",
    "水族宠物",
    "🐠",
    "暹罗斗鱼",
    {
      commitment: 0.5,
      activity: 0.1,
      social: 0.1,
      patience: 0.55,
      care: 0.5,
      resources: 0.5,
      specialist: 0.55,
      independence: 1,
      adaptability: 0.35,
      trainability: 0.1,
      sensitivity: 0.6,
    },
    "你享受安静观察并愿意维护稳定环境。暹罗斗鱼需要合适缸体、加热、过滤和稳定水质。",
  ),
  profile(
    "guppy",
    "灵动群游型",
    "水族宠物",
    "🐟",
    "孔雀鱼",
    {
      commitment: 0.6,
      activity: 0.2,
      social: 0.35,
      patience: 0.75,
      care: 0.75,
      resources: 0.55,
      specialist: 0.75,
      independence: 0.85,
      adaptability: 0.55,
      trainability: 0.1,
      sensitivity: 0.7,
    },
    "你喜欢观察活跃鱼群，也愿意学习水质管理。孔雀鱼繁殖快，需要成熟水体和后代安置计划。",
  ),
  profile(
    "neon-tetra",
    "安静群落型",
    "水族宠物",
    "🐟",
    "霓虹灯鱼",
    {
      commitment: 0.7,
      activity: 0.15,
      social: 0.3,
      patience: 0.95,
      care: 0.95,
      resources: 0.75,
      specialist: 1,
      independence: 0.9,
      adaptability: 0.3,
      trainability: 0.1,
      sensitivity: 0.95,
    },
    "你愿意耐心维护稳定环境并欣赏群游生态。霓虹灯鱼需要成熟水族箱、成群饲养和合适混养伙伴。",
  ),
  profile(
    "pause",
    "当前更适合先体验",
    "养宠准备",
    "🌱",
    "云养宠或志愿服务",
    { commitment: 1, resources: 1, safety: 1 },
    "养宠的现实条件比人格匹配更重要。先补齐许可、预算、时间或照护支持，是对你和动物都负责的选择。",
  ),
];
